apiVersion: v1
kind: Service
metadata:
  name: scores-api-stable
  namespace: argo-rollouts-demo
  labels:
    app: scores-api
    role: stable
spec:
  selector:
    app: scores-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: scores-api-canary
  namespace: argo-rollouts-demo
  labels:
    app: scores-api
    role: canary
spec:
  selector:
    app: scores-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
